// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[tenant]/admin/_middleware.ts";
import * as $1 from "./routes/[tenant]/admin/index.tsx";
import * as $2 from "./routes/_404.tsx";
import * as $3 from "./routes/_500.tsx";
import * as $4 from "./routes/_app.tsx";
import * as $5 from "./routes/_middleware.ts";
import * as $6 from "./routes/about.tsx";
import * as $7 from "./routes/api/joke.ts";
import * as $8 from "./routes/api/random-uuid.ts";
import * as $9 from "./routes/blog/[slug].tsx";
import * as $10 from "./routes/countdown.tsx";
import * as $11 from "./routes/define.tsx";
import * as $12 from "./routes/github/[username].tsx";
import * as $13 from "./routes/greet/[name].tsx";
import * as $14 from "./routes/html.tsx";
import * as $15 from "./routes/index.tsx";
import * as $16 from "./routes/myHandler.ts";
import * as $17 from "./routes/page.tsx";
import * as $18 from "./routes/project/[id].tsx";
import * as $19 from "./routes/search.tsx";
import * as $20 from "./routes/subscribe.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/my-island.tsx";
import * as $$3 from "./islands/other-island.tsx";

const manifest = {
  routes: {
    "./routes/[tenant]/admin/_middleware.ts": $0,
    "./routes/[tenant]/admin/index.tsx": $1,
    "./routes/_404.tsx": $2,
    "./routes/_500.tsx": $3,
    "./routes/_app.tsx": $4,
    "./routes/_middleware.ts": $5,
    "./routes/about.tsx": $6,
    "./routes/api/joke.ts": $7,
    "./routes/api/random-uuid.ts": $8,
    "./routes/blog/[slug].tsx": $9,
    "./routes/countdown.tsx": $10,
    "./routes/define.tsx": $11,
    "./routes/github/[username].tsx": $12,
    "./routes/greet/[name].tsx": $13,
    "./routes/html.tsx": $14,
    "./routes/index.tsx": $15,
    "./routes/myHandler.ts": $16,
    "./routes/page.tsx": $17,
    "./routes/project/[id].tsx": $18,
    "./routes/search.tsx": $19,
    "./routes/subscribe.tsx": $20,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/my-island.tsx": $$2,
    "./islands/other-island.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
