// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/api/random-uuid.ts";
import * as $5 from "./routes/countdown.tsx";
import * as $6 from "./routes/define.tsx";
import * as $7 from "./routes/github/[username].tsx";
import * as $8 from "./routes/greet/[name].tsx";
import * as $9 from "./routes/html.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/page.tsx";
import * as $12 from "./routes/search.tsx";
import * as $13 from "./routes/subscribe.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/my-island.tsx";
import * as $$3 from "./islands/other-island.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/api/random-uuid.ts": $4,
    "./routes/countdown.tsx": $5,
    "./routes/define.tsx": $6,
    "./routes/github/[username].tsx": $7,
    "./routes/greet/[name].tsx": $8,
    "./routes/html.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/page.tsx": $11,
    "./routes/search.tsx": $12,
    "./routes/subscribe.tsx": $13,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/my-island.tsx": $$2,
    "./islands/other-island.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
